image: ubuntu

stages:
  - build

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y inkscape make optipng python3-pip fonts-roboto-slab j2cli --no-install-recommends
    - make svg
    - make print
    - make png
    - make png_print
    - make ci
  artifacts:
    paths:
      - release.zip
