image: ubuntu

stages:
  - install_dependencies
  - build
  - package

install_dependencies-job: 
  stage: install_dependencies
  script:
    - sudo apt-get update && sudo apt-get install -y inkscape optipng python3-pip fonts-roboto-slab
    - sudo pip3 install j2cli

build-job:
  stage: build
  script:
    - make svg
    - make print
    - make png
    - make png_print

package-job:
  stage: package
  script:
    - make ci
  artifacts:
    paths:
      - release.zip
